language: python
python:
  - "3.3"
  - "3.5"
  - "3.6"

# Setup anaconda
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda create --yes -n env_name python=$TRAVIS_PYTHON_VERSION pip lxml matplotlib numpy scipy pandas mplleaflet folium seawater oceans netCDF4
  - source activate env_name

# Run test
script:
  - python tJOG.py loop.gpx
  -python tJOG.py -ADL loop.gpx